appId: com.ultratechplus.clync
---
# flows:
#   - 'subFolder/*'
# includeTags:
#   - tagNameToInclude
# excludeTags:
#   - tagNameToExclude
executionOrder:
  continueOnFailure: false # default is true
  flowsOrder:
    - Login
    - Community


# # Customised test output directory
# testOutputDir: test_output_directory

# # Cloud only config options
# baselineBranch: main
# notifications:
#   email:
#     enabled: true
#     recipients:
#       - john@example.com

# # Platform Configuration
# platform:
#   ios:
#     snapshotKeyHonorModalViews: false
#     disableAnimations: true
#   android:
#     disableAnimations: true